import{S as u,i as a}from"./assets/vendor-46aac873.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const l="/goit-js-hw-11/assets/octagon-e3b0c442.svg",m=document.querySelector(".form"),c=document.querySelector(".gallery");document.querySelector(".loader");const p=new u(".gallery a",{captionsData:"alt",captionDelay:250});m.addEventListener("submit",h);function h(t){t.preventDefault();const o=t.currentTarget.elements.input.value;if(c.innerHTML="",!o.trim()){a.show({title:"❕",theme:"light",message:"Please, fill in the search field",messageSize:"20px",messageColor:"#808080",backgroundColor:"#e7fc44",position:"topLeft",timeout:3e3});return}v();const s=new URLSearchParams({key:"41838546-9d950a50e841202e6c289d2dd",q:o,image_type:"photo",orientation:"horizontal",safesearch:"true"});f(s).then(i=>{i.hits.length===0&&a.show({iconUrl:l,theme:"dark",message:"Sorry, there are no images matching your search query. Please try again!",messageSize:"16px",messageColor:"white",backgroundColor:"#EF4040",position:"topRight",timeout:5e3}),c.innerHTML=g(i.hits),p.refresh()}).catch(i=>{console.error(i),y()}).finally(()=>{L(),t.currentTarget.reset()})}function f(t){return fetch(`https://pixabay.com/api/?${t}`).then(s=>{if(!s.ok)throw new Error(s.status);return s.json()})}function g(t){return t.map(({webformatURL:o,largeImageURL:s,tags:i,likes:e,views:r,comments:n,downloads:d})=>`<li class="gallery-item">
          <a class="gallery-link" href="${s}">
            <img
              class="gallery-image"
              src="${o}"
              alt="${i}"
            />
          </a>
          <div class="container-additional-info">
            <div class="container-descr-inner"><p class="description">Likes</p><span class="description-value">${e}</span></div>
            <div class="container-descr-inner"><p class="description">Views</p><span class="description-value">${r}</span></div>
            <div class="container-descr-inner"><p class="description">Comments</p><span class="description-value">${n}</span></div>
            <div class="container-descr-inner"><p class="description">Downloads</p><span class="description-value">${d}</span></div>
          </div>
        </li>`).join("")}function y(){c.innerHTML="",a.show({iconUrl:l,theme:"dark",message:"Sorry, there is a problem with connection with the server.",messageSize:"16px",messageColor:"white",backgroundColor:"#EF4040",position:"center",timeout:5e3})}function v(){document.querySelector(".loader").classList.remove("is-hidden")}function L(){document.querySelector(".loader").classList.add("is-hidden")}
//# sourceMappingURL=commonHelpers.js.map
